name: release CI-CD 
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - uses: hadolint/hadolint-action@v3.1.0
        with:
           dockerfile: Dockerfile
      - name: "Build Image"
        run: docker build --tag=megharba/ojetbuilder:latest ./
      - name: "run containers"
        run: docker run -d --rm --name=esgiOjetBuilder megharba/ojetbuilder:latest 
      - name: "check containers"
        run: docker ps
      - name: "stop containers"
        run: docker stop esgiOjetBuilder
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         if: startsWith(github.ref, 'refs/tags/')
         with:
           username: bmegharba
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Push if on `main`
         uses: docker/build-push-action@v4
         if: startsWith(github.ref, 'refs/tags/')
         with:
           push: true
           context: /app
           tags: megharba/esgiojetbuilder:${{ github.ref_name }}
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         if: contains('refs/heads/main', github.ref)
         with:
          username: megharba
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Push if on `main`
         uses: docker/build-push-action@v4
         if: contains('refs/heads/main', github.ref)
         with:
           push: true
           context: /app
           tags: megharba/esgiojetbuilder:latest
       