name: Bonjour Bruno
on:
  - pull_request
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - uses: hadolint/hadolint-action@v3.1.0
        with:
           dockerfile: Dockerfile
      - name: "Build Image"
        run: docker build -t megharba/ojetbuilder:1.0.0 ./
      - name: "run containers"
        run: docker run -it --rm  megharba/ojetbuilder:latest bash -c "cat ./README.md"